# CLI tools live in mise/config.toml. Keep here only what mise cannot provide
# (bootstrap, system libs/tools, GUI apps, fonts).
brew "mise"
brew "git"
brew "vim"
brew "clang-format"
brew "ffmpeg"
brew "nasm"
brew "nkf"
brew "pipes-sh"
brew "podman"
brew "tree"
brew "watch"
brew "wget"
cask "alacritty"
cask "discord"
cask "font-hackgen-nerd"
cask "hiddenbar"
cask "karabiner-elements"
cask "keycastr"
cask "meetingbar"
cask "raycast"
cask "rectangle"
cask "slack"
cask "visual-studio-code"
cask "zoom"
