[tools]
uv = "latest"
python = "latest"
node = "latest"
go = "latest"
ruby = "latest"
kubectl = "latest"
minikube = "latest"
"npm:gtop" = "latest"

[settings]
lockfile = true
npm.package_manager = "npm"
