[tools]
uv = "latest"
python = "latest"
node = "latest"
go = "latest"
ruby = "latest"
kubectl = "latest"
minikube = "latest"
"npm:gtop" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:theryangeary/choose" = "latest"
"aqua:muesli/duf" = "latest"
"vfox:jdx/vfox-eza" = "latest"
"aqua:bootandy/dust" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:antonmedv/fx" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:x-motemen/ghq" = "latest"
"aqua:dandavison/delta" = "latest"
"aqua:orf/gping" = "latest"
"aqua:hadolint/hadolint" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:jesseduffield/lazydocker" = "latest"
"aqua:mas-cli/mas" = "latest"
"aqua:dalance/procs" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:phiresky/ripgrep-all" = "latest"
"aqua:rs/curlie" = "latest"
"aqua:dduan/tre" = "latest"
"aqua:zquestz/s" = "latest"
"pipx:httpie" = "latest"
"pipx:glances" = "latest"
"aqua:herdrdev/herdr" = "latest"
"aqua:starship/starship" = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
"aqua:tmux/tmux-builds" = "latest"
"github:yt-dlp/yt-dlp" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"

[settings]
lockfile = true
npm.package_manager = "npm"
